// Mocks generated by Mockito 5.4.6 from annotations
// in sjgtv/test/data/repositories/source_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:dio/src/adapter.dart' as _i5;
import 'package:dio/src/cancel_token.dart' as _i18;
import 'package:dio/src/dio.dart' as _i9;
import 'package:dio/src/dio_mixin.dart' as _i7;
import 'package:dio/src/options.dart' as _i4;
import 'package:dio/src/response.dart' as _i8;
import 'package:dio/src/transformer.dart' as _i6;
import 'package:mockito/mockito.dart' as _i2;
import 'package:sjgtv/core/arch/errors/failures.dart' as _i1;
import 'package:sjgtv/core/arch/errors/result.dart' as _i3;
import 'package:sjgtv/data/datasources/local_datasource.dart' as _i10;
import 'package:sjgtv/domain/entities/favorite.dart' as _i16;
import 'package:sjgtv/domain/entities/proxy.dart' as _i13;
import 'package:sjgtv/domain/entities/settings.dart' as _i17;
import 'package:sjgtv/domain/entities/source.dart' as _i12;
import 'package:sjgtv/domain/entities/tag.dart' as _i14;
import 'package:sjgtv/domain/entities/watch_history.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E extends _i1.Failure> extends _i2.SmartFake
    implements _i3.Result<T, E> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_1 extends _i2.SmartFake implements _i4.BaseOptions {
  _FakeBaseOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_2 extends _i2.SmartFake
    implements _i5.HttpClientAdapter {
  _FakeHttpClientAdapter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_3 extends _i2.SmartFake implements _i6.Transformer {
  _FakeTransformer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_4 extends _i2.SmartFake implements _i7.Interceptors {
  _FakeInterceptors_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_5<T1> extends _i2.SmartFake implements _i8.Response<T1> {
  _FakeResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_6 extends _i2.SmartFake implements _i9.Dio {
  _FakeDio_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i2.Mock implements _i10.LocalDataSource {
  MockLocalDataSource() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.Result<List<_i12.Source>, _i1.Failure>> getAllSources() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSources, []),
            returnValue:
                _i11.Future<_i3.Result<List<_i12.Source>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i12.Source>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllSources, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i12.Source>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i12.Source, _i1.Failure>> addSource(
    _i12.Source? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSource, [source]),
            returnValue:
                _i11.Future<_i3.Result<_i12.Source, _i1.Failure>>.value(
                  _FakeResult_0<_i12.Source, _i1.Failure>(
                    this,
                    Invocation.method(#addSource, [source]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i12.Source, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i12.Source, _i1.Failure>> updateSource(
    _i12.Source? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSource, [source]),
            returnValue:
                _i11.Future<_i3.Result<_i12.Source, _i1.Failure>>.value(
                  _FakeResult_0<_i12.Source, _i1.Failure>(
                    this,
                    Invocation.method(#updateSource, [source]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i12.Source, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> deleteSource(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSource, [uuid]),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteSource, [uuid]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<List<_i13.Proxy>, _i1.Failure>> getAllProxies() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProxies, []),
            returnValue:
                _i11.Future<_i3.Result<List<_i13.Proxy>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i13.Proxy>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllProxies, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i13.Proxy>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<List<_i13.Proxy>, _i1.Failure>> getEnabledProxies() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledProxies, []),
            returnValue:
                _i11.Future<_i3.Result<List<_i13.Proxy>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i13.Proxy>, _i1.Failure>(
                    this,
                    Invocation.method(#getEnabledProxies, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i13.Proxy>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i13.Proxy, _i1.Failure>> addProxy(
    _i13.Proxy? proxy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProxy, [proxy]),
            returnValue: _i11.Future<_i3.Result<_i13.Proxy, _i1.Failure>>.value(
              _FakeResult_0<_i13.Proxy, _i1.Failure>(
                this,
                Invocation.method(#addProxy, [proxy]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<_i13.Proxy, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i13.Proxy, _i1.Failure>> updateProxy(
    _i13.Proxy? proxy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProxy, [proxy]),
            returnValue: _i11.Future<_i3.Result<_i13.Proxy, _i1.Failure>>.value(
              _FakeResult_0<_i13.Proxy, _i1.Failure>(
                this,
                Invocation.method(#updateProxy, [proxy]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<_i13.Proxy, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> deleteProxy(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProxy, [uuid]),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteProxy, [uuid]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<List<_i14.Tag>, _i1.Failure>> getAllTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, []),
            returnValue:
                _i11.Future<_i3.Result<List<_i14.Tag>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i14.Tag>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllTags, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i14.Tag>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i14.Tag, _i1.Failure>> addTag(_i14.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#addTag, [tag]),
            returnValue: _i11.Future<_i3.Result<_i14.Tag, _i1.Failure>>.value(
              _FakeResult_0<_i14.Tag, _i1.Failure>(
                this,
                Invocation.method(#addTag, [tag]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<_i14.Tag, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i14.Tag, _i1.Failure>> updateTag(_i14.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#updateTag, [tag]),
            returnValue: _i11.Future<_i3.Result<_i14.Tag, _i1.Failure>>.value(
              _FakeResult_0<_i14.Tag, _i1.Failure>(
                this,
                Invocation.method(#updateTag, [tag]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<_i14.Tag, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> deleteTag(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [uuid]),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteTag, [uuid]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i15.WatchHistory, _i1.Failure>>
  addOrUpdateWatchHistory(_i15.WatchHistory? history) =>
      (super.noSuchMethod(
            Invocation.method(#addOrUpdateWatchHistory, [history]),
            returnValue:
                _i11.Future<_i3.Result<_i15.WatchHistory, _i1.Failure>>.value(
                  _FakeResult_0<_i15.WatchHistory, _i1.Failure>(
                    this,
                    Invocation.method(#addOrUpdateWatchHistory, [history]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i15.WatchHistory, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<List<_i15.WatchHistory>, _i1.Failure>>
  getAllWatchHistories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWatchHistories, []),
            returnValue:
                _i11.Future<
                  _i3.Result<List<_i15.WatchHistory>, _i1.Failure>
                >.value(
                  _FakeResult_0<List<_i15.WatchHistory>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllWatchHistories, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i15.WatchHistory>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<List<_i15.WatchHistory>, _i1.Failure>>
  getWatchHistoriesByMovie(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchHistoriesByMovie, [movieId]),
            returnValue:
                _i11.Future<
                  _i3.Result<List<_i15.WatchHistory>, _i1.Failure>
                >.value(
                  _FakeResult_0<List<_i15.WatchHistory>, _i1.Failure>(
                    this,
                    Invocation.method(#getWatchHistoriesByMovie, [movieId]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i15.WatchHistory>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> deleteWatchHistory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWatchHistory, [id]),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteWatchHistory, [id]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> clearAllWatchHistories() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllWatchHistories, []),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#clearAllWatchHistories, []),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<List<_i16.Favorite>, _i1.Failure>> getAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFavorites, []),
            returnValue:
                _i11.Future<_i3.Result<List<_i16.Favorite>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i16.Favorite>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllFavorites, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<List<_i16.Favorite>, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i16.Favorite, _i1.Failure>> addFavorite(
    _i16.Favorite? favorite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [favorite]),
            returnValue:
                _i11.Future<_i3.Result<_i16.Favorite, _i1.Failure>>.value(
                  _FakeResult_0<_i16.Favorite, _i1.Failure>(
                    this,
                    Invocation.method(#addFavorite, [favorite]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i16.Favorite, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> deleteFavorite(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [uuid]),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteFavorite, [uuid]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<bool, _i1.Failure>> isFavorite(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [movieId]),
            returnValue: _i11.Future<_i3.Result<bool, _i1.Failure>>.value(
              _FakeResult_0<bool, _i1.Failure>(
                this,
                Invocation.method(#isFavorite, [movieId]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<bool, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<void, _i1.Failure>> unfavorite(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#unfavorite, [movieId]),
            returnValue: _i11.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#unfavorite, [movieId]),
              ),
            ),
          )
          as _i11.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>>.value(
                  _FakeResult_0<_i17.Settings, _i1.Failure>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>> saveSettings(
    _i17.Settings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue:
                _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>>.value(
                  _FakeResult_0<_i17.Settings, _i1.Failure>(
                    this,
                    Invocation.method(#saveSettings, [settings]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>>);

  @override
  _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>> updateSettings(
    _i17.Settings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [settings]),
            returnValue:
                _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>>.value(
                  _FakeResult_0<_i17.Settings, _i1.Failure>(
                    this,
                    Invocation.method(#updateSettings, [settings]),
                  ),
                ),
          )
          as _i11.Future<_i3.Result<_i17.Settings, _i1.Failure>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i2.Mock implements _i9.Dio {
  MockDio() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i4.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_1(this, Invocation.getter(#options)),
          )
          as _i4.BaseOptions);

  @override
  _i5.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_2(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i5.HttpClientAdapter);

  @override
  _i6.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_3(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i6.Transformer);

  @override
  _i7.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_4(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i7.Interceptors);

  @override
  set options(_i4.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i5.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i6.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i8.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i4.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i18.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i4.FileAccessMode? fileAccessMode = _i4.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<dynamic>>);

  @override
  _i11.Future<_i8.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i4.ProgressCallback? onReceiveProgress,
    _i18.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i4.FileAccessMode? fileAccessMode = _i4.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<dynamic>>);

  @override
  _i11.Future<_i8.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i18.CancelToken? cancelToken,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i18.CancelToken? cancelToken,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> fetch<T>(_i4.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i9.Dio clone({
    _i4.BaseOptions? options,
    _i7.Interceptors? interceptors,
    _i5.HttpClientAdapter? httpClientAdapter,
    _i6.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_6(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i9.Dio);
}
