// Mocks generated by Mockito 5.4.6 from annotations
// in sjgtv/test/data/repositories/watch_history_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i2;
import 'package:sjgtv/core/arch/errors/failures.dart' as _i1;
import 'package:sjgtv/core/arch/errors/result.dart' as _i3;
import 'package:sjgtv/data/datasources/local_datasource.dart' as _i4;
import 'package:sjgtv/domain/entities/favorite.dart' as _i10;
import 'package:sjgtv/domain/entities/proxy.dart' as _i7;
import 'package:sjgtv/domain/entities/settings.dart' as _i11;
import 'package:sjgtv/domain/entities/source.dart' as _i6;
import 'package:sjgtv/domain/entities/tag.dart' as _i8;
import 'package:sjgtv/domain/entities/watch_history.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E extends _i1.Failure> extends _i2.SmartFake
    implements _i3.Result<T, E> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i2.Mock implements _i4.LocalDataSource {
  MockLocalDataSource() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<List<_i6.Source>, _i1.Failure>> getAllSources() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSources, []),
            returnValue:
                _i5.Future<_i3.Result<List<_i6.Source>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i6.Source>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllSources, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i6.Source>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i6.Source, _i1.Failure>> addSource(
    _i6.Source? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSource, [source]),
            returnValue: _i5.Future<_i3.Result<_i6.Source, _i1.Failure>>.value(
              _FakeResult_0<_i6.Source, _i1.Failure>(
                this,
                Invocation.method(#addSource, [source]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<_i6.Source, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i6.Source, _i1.Failure>> updateSource(
    _i6.Source? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSource, [source]),
            returnValue: _i5.Future<_i3.Result<_i6.Source, _i1.Failure>>.value(
              _FakeResult_0<_i6.Source, _i1.Failure>(
                this,
                Invocation.method(#updateSource, [source]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<_i6.Source, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteSource(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSource, [uuid]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteSource, [uuid]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i7.Proxy>, _i1.Failure>> getAllProxies() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProxies, []),
            returnValue:
                _i5.Future<_i3.Result<List<_i7.Proxy>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i7.Proxy>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllProxies, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i7.Proxy>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i7.Proxy>, _i1.Failure>> getEnabledProxies() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledProxies, []),
            returnValue:
                _i5.Future<_i3.Result<List<_i7.Proxy>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i7.Proxy>, _i1.Failure>(
                    this,
                    Invocation.method(#getEnabledProxies, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i7.Proxy>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i7.Proxy, _i1.Failure>> addProxy(_i7.Proxy? proxy) =>
      (super.noSuchMethod(
            Invocation.method(#addProxy, [proxy]),
            returnValue: _i5.Future<_i3.Result<_i7.Proxy, _i1.Failure>>.value(
              _FakeResult_0<_i7.Proxy, _i1.Failure>(
                this,
                Invocation.method(#addProxy, [proxy]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<_i7.Proxy, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i7.Proxy, _i1.Failure>> updateProxy(
    _i7.Proxy? proxy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProxy, [proxy]),
            returnValue: _i5.Future<_i3.Result<_i7.Proxy, _i1.Failure>>.value(
              _FakeResult_0<_i7.Proxy, _i1.Failure>(
                this,
                Invocation.method(#updateProxy, [proxy]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<_i7.Proxy, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteProxy(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProxy, [uuid]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteProxy, [uuid]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i8.Tag>, _i1.Failure>> getAllTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, []),
            returnValue:
                _i5.Future<_i3.Result<List<_i8.Tag>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i8.Tag>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllTags, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i8.Tag>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i8.Tag, _i1.Failure>> addTag(_i8.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#addTag, [tag]),
            returnValue: _i5.Future<_i3.Result<_i8.Tag, _i1.Failure>>.value(
              _FakeResult_0<_i8.Tag, _i1.Failure>(
                this,
                Invocation.method(#addTag, [tag]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<_i8.Tag, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i8.Tag, _i1.Failure>> updateTag(_i8.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#updateTag, [tag]),
            returnValue: _i5.Future<_i3.Result<_i8.Tag, _i1.Failure>>.value(
              _FakeResult_0<_i8.Tag, _i1.Failure>(
                this,
                Invocation.method(#updateTag, [tag]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<_i8.Tag, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteTag(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [uuid]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteTag, [uuid]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i9.WatchHistory, _i1.Failure>> addOrUpdateWatchHistory(
    _i9.WatchHistory? history,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOrUpdateWatchHistory, [history]),
            returnValue:
                _i5.Future<_i3.Result<_i9.WatchHistory, _i1.Failure>>.value(
                  _FakeResult_0<_i9.WatchHistory, _i1.Failure>(
                    this,
                    Invocation.method(#addOrUpdateWatchHistory, [history]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i9.WatchHistory, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i9.WatchHistory>, _i1.Failure>>
  getAllWatchHistories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWatchHistories, []),
            returnValue:
                _i5.Future<
                  _i3.Result<List<_i9.WatchHistory>, _i1.Failure>
                >.value(
                  _FakeResult_0<List<_i9.WatchHistory>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllWatchHistories, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i9.WatchHistory>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i9.WatchHistory>, _i1.Failure>>
  getWatchHistoriesByMovie(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchHistoriesByMovie, [movieId]),
            returnValue:
                _i5.Future<
                  _i3.Result<List<_i9.WatchHistory>, _i1.Failure>
                >.value(
                  _FakeResult_0<List<_i9.WatchHistory>, _i1.Failure>(
                    this,
                    Invocation.method(#getWatchHistoriesByMovie, [movieId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i9.WatchHistory>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteWatchHistory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWatchHistory, [id]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteWatchHistory, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> clearAllWatchHistories() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllWatchHistories, []),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#clearAllWatchHistories, []),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i10.Favorite>, _i1.Failure>> getAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFavorites, []),
            returnValue:
                _i5.Future<_i3.Result<List<_i10.Favorite>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i10.Favorite>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllFavorites, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i10.Favorite>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i10.Favorite, _i1.Failure>> addFavorite(
    _i10.Favorite? favorite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [favorite]),
            returnValue:
                _i5.Future<_i3.Result<_i10.Favorite, _i1.Failure>>.value(
                  _FakeResult_0<_i10.Favorite, _i1.Failure>(
                    this,
                    Invocation.method(#addFavorite, [favorite]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i10.Favorite, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteFavorite(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [uuid]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteFavorite, [uuid]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<bool, _i1.Failure>> isFavorite(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [movieId]),
            returnValue: _i5.Future<_i3.Result<bool, _i1.Failure>>.value(
              _FakeResult_0<bool, _i1.Failure>(
                this,
                Invocation.method(#isFavorite, [movieId]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<bool, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> unfavorite(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#unfavorite, [movieId]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#unfavorite, [movieId]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>>.value(
                  _FakeResult_0<_i11.Settings, _i1.Failure>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>> saveSettings(
    _i11.Settings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue:
                _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>>.value(
                  _FakeResult_0<_i11.Settings, _i1.Failure>(
                    this,
                    Invocation.method(#saveSettings, [settings]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>> updateSettings(
    _i11.Settings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [settings]),
            returnValue:
                _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>>.value(
                  _FakeResult_0<_i11.Settings, _i1.Failure>(
                    this,
                    Invocation.method(#updateSettings, [settings]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i11.Settings, _i1.Failure>>);
}
