# 与 base/build.yaml 一致，版本以 base 为准
targets:
  $default:
    builders:
      riverpod_generator:
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
          provider_name_suffix: ""
          provider_family_name_suffix: ""
