# Flutter 官方 gen-l10n 配置（app 国际化）
arb-dir: lib/l10n_arb
template-arb-file: app_zh_CN.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n_gen
nullable-getter: false
preferred-supported-locales: ['zh_CN', 'en', 'zh_HK']
