// Mocks generated by Mockito 5.4.6 from annotations
// in sjgtv/test/src/favorite/provider/favorites_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sjgtv/core/arch/errors/failures.dart' as _i3;
import 'package:sjgtv/core/arch/errors/result.dart' as _i4;
import 'package:sjgtv/domain/entities/favorite.dart' as _i7;
import 'package:sjgtv/domain/repositories/favorite_repository.dart' as _i2;
import 'package:sjgtv/domain/usecases/add_favorite_usecase.dart' as _i8;
import 'package:sjgtv/domain/usecases/delete_favorite_usecase.dart' as _i9;
import 'package:sjgtv/domain/usecases/get_all_favorites_usecase.dart' as _i5;
import 'package:sjgtv/domain/usecases/is_favorite_usecase.dart' as _i10;
import 'package:sjgtv/domain/usecases/unfavorite_usecase.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoriteRepository_0 extends _i1.SmartFake
    implements _i2.FavoriteRepository {
  _FakeFavoriteRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResult_1<T, E extends _i3.Failure> extends _i1.SmartFake
    implements _i4.Result<T, E> {
  _FakeResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllFavoritesUseCase extends _i1.Mock
    implements _i5.GetAllFavoritesUseCase {
  MockGetAllFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoriteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoriteRepository);

  @override
  _i6.Future<_i4.Result<List<_i7.Favorite>, _i3.Failure>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i6.Future<_i4.Result<List<_i7.Favorite>, _i3.Failure>>.value(
                  _FakeResult_1<List<_i7.Favorite>, _i3.Failure>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Result<List<_i7.Favorite>, _i3.Failure>>);
}

/// A class which mocks [AddFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFavoriteUseCase extends _i1.Mock
    implements _i8.AddFavoriteUseCase {
  MockAddFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoriteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoriteRepository);

  @override
  _i6.Future<_i4.Result<_i7.Favorite, _i3.Failure>> call(
    _i7.Favorite? favorite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [favorite]),
            returnValue:
                _i6.Future<_i4.Result<_i7.Favorite, _i3.Failure>>.value(
                  _FakeResult_1<_i7.Favorite, _i3.Failure>(
                    this,
                    Invocation.method(#call, [favorite]),
                  ),
                ),
          )
          as _i6.Future<_i4.Result<_i7.Favorite, _i3.Failure>>);
}

/// A class which mocks [DeleteFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteFavoriteUseCase extends _i1.Mock
    implements _i9.DeleteFavoriteUseCase {
  MockDeleteFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoriteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoriteRepository);

  @override
  _i6.Future<_i4.Result<void, _i3.Failure>> call(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#call, [uuid]),
            returnValue: _i6.Future<_i4.Result<void, _i3.Failure>>.value(
              _FakeResult_1<void, _i3.Failure>(
                this,
                Invocation.method(#call, [uuid]),
              ),
            ),
          )
          as _i6.Future<_i4.Result<void, _i3.Failure>>);
}

/// A class which mocks [IsFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsFavoriteUseCase extends _i1.Mock implements _i10.IsFavoriteUseCase {
  MockIsFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoriteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoriteRepository);

  @override
  _i6.Future<_i4.Result<bool, _i3.Failure>> call(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [movieId]),
            returnValue: _i6.Future<_i4.Result<bool, _i3.Failure>>.value(
              _FakeResult_1<bool, _i3.Failure>(
                this,
                Invocation.method(#call, [movieId]),
              ),
            ),
          )
          as _i6.Future<_i4.Result<bool, _i3.Failure>>);
}

/// A class which mocks [UnfavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnfavoriteUseCase extends _i1.Mock implements _i11.UnfavoriteUseCase {
  MockUnfavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoriteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoriteRepository);

  @override
  _i6.Future<_i4.Result<void, _i3.Failure>> call(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [movieId]),
            returnValue: _i6.Future<_i4.Result<void, _i3.Failure>>.value(
              _FakeResult_1<void, _i3.Failure>(
                this,
                Invocation.method(#call, [movieId]),
              ),
            ),
          )
          as _i6.Future<_i4.Result<void, _i3.Failure>>);
}
