// Mocks generated by Mockito 5.4.6 from annotations
// in sjgtv/test/domain/usecases/add_favorite_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i2;
import 'package:sjgtv/core/arch/errors/failures.dart' as _i1;
import 'package:sjgtv/core/arch/errors/result.dart' as _i3;
import 'package:sjgtv/domain/entities/favorite.dart' as _i6;
import 'package:sjgtv/domain/repositories/favorite_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E extends _i1.Failure> extends _i2.SmartFake
    implements _i3.Result<T, E> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i2.Mock
    implements _i4.FavoriteRepository {
  MockFavoriteRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<List<_i6.Favorite>, _i1.Failure>> getAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFavorites, []),
            returnValue:
                _i5.Future<_i3.Result<List<_i6.Favorite>, _i1.Failure>>.value(
                  _FakeResult_0<List<_i6.Favorite>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllFavorites, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i6.Favorite>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<_i6.Favorite, _i1.Failure>> addFavorite(
    _i6.Favorite? favorite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [favorite]),
            returnValue:
                _i5.Future<_i3.Result<_i6.Favorite, _i1.Failure>>.value(
                  _FakeResult_0<_i6.Favorite, _i1.Failure>(
                    this,
                    Invocation.method(#addFavorite, [favorite]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i6.Favorite, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteFavorite(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [uuid]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteFavorite, [uuid]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<bool, _i1.Failure>> isFavorite(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [movieId]),
            returnValue: _i5.Future<_i3.Result<bool, _i1.Failure>>.value(
              _FakeResult_0<bool, _i1.Failure>(
                this,
                Invocation.method(#isFavorite, [movieId]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<bool, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> unfavorite(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#unfavorite, [movieId]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#unfavorite, [movieId]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);
}
