// Mocks generated by Mockito 5.4.6 from annotations
// in sjgtv/test/domain/usecases/get_all_watch_histories_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i2;
import 'package:sjgtv/core/arch/errors/failures.dart' as _i1;
import 'package:sjgtv/core/arch/errors/result.dart' as _i3;
import 'package:sjgtv/domain/entities/watch_history.dart' as _i6;
import 'package:sjgtv/domain/repositories/watch_history_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E extends _i1.Failure> extends _i2.SmartFake
    implements _i3.Result<T, E> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WatchHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchHistoryRepository extends _i2.Mock
    implements _i4.WatchHistoryRepository {
  MockWatchHistoryRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<_i6.WatchHistory, _i1.Failure>> addOrUpdateHistory(
    _i6.WatchHistory? history,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOrUpdateHistory, [history]),
            returnValue:
                _i5.Future<_i3.Result<_i6.WatchHistory, _i1.Failure>>.value(
                  _FakeResult_0<_i6.WatchHistory, _i1.Failure>(
                    this,
                    Invocation.method(#addOrUpdateHistory, [history]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<_i6.WatchHistory, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i6.WatchHistory>, _i1.Failure>>
  getAllHistories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllHistories, []),
            returnValue:
                _i5.Future<
                  _i3.Result<List<_i6.WatchHistory>, _i1.Failure>
                >.value(
                  _FakeResult_0<List<_i6.WatchHistory>, _i1.Failure>(
                    this,
                    Invocation.method(#getAllHistories, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i6.WatchHistory>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<List<_i6.WatchHistory>, _i1.Failure>>
  getHistoriesByMovie(String? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoriesByMovie, [movieId]),
            returnValue:
                _i5.Future<
                  _i3.Result<List<_i6.WatchHistory>, _i1.Failure>
                >.value(
                  _FakeResult_0<List<_i6.WatchHistory>, _i1.Failure>(
                    this,
                    Invocation.method(#getHistoriesByMovie, [movieId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Result<List<_i6.WatchHistory>, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> deleteHistory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [id]),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#deleteHistory, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> clearAllHistories() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllHistories, []),
            returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
              _FakeResult_0<void, _i1.Failure>(
                this,
                Invocation.method(#clearAllHistories, []),
              ),
            ),
          )
          as _i5.Future<_i3.Result<void, _i1.Failure>>);
}
